### ISSUE TITLE
"FlimboxFbd: b4w16c4 decoder not tested."

### ISSUE THREAD

**Issue by ghost** [cgohlke/lfdfiles#1]
Attempted to open Flimbox fbd files for 20MHz measurements. The files fail to decode and receive this message "FlimboxFbd: b4w16c4 decoder not tested. Please submit a FBD file to https://github.com/cgohlke/lfdfiles" . 
I have attached a few of the .fbd files with their accompanying .fbs files.

[Example 20MHz fbd.zip](https://github.com/cgohlke/lfdfiles/files/14456415/Example.20MHz.fbd.zip)

**Comment by cgohlke** [comment]
Thank you for submitting the files. 

I could not find anything wrong with the decoder settings according to the little information I have. I will double check again.

It seems neither SimFCS nor VistaVision are able to correctly decode the files either. Can you provide exported data or screenshots of the expected average histograms and/or images per channel?

The file claims to contain line markers. This library does not use line markers, only frame markers to decode images. That could explain the problems with image reconstruction.

According to the metadata only 2 channels are used. The firmware supports 4 channels. Which decoded channels did you look at?

**Comment by ghost** [comment]
Thank you for looking into this. I am still quite new to the using the FLIMBox and these FLIM file types, so the lfdfiles library and your assistance is much appreciated. 

Previously I have used the FlimboxFbd function to successfully decoded a set of images which were taken at 80MHz laser frequency, but the recent images taken with the FLIMBox set to 20MHz do not decode. This makes me think the issue may actually be somehow related to the settings of our FLIMBox changing when the laser frequency is changed. This being said, the FLIMBox is only ever set to frames so I’m not too sure why the original files I attached contain line markers.

Hopefully the following attachments can be of use in figuring out where the problem lies. 
-	Screenshot of the histogram from a previous successfully decoded (80MHz) image – shows the measurement from two individual pixels within the image. This is basically what I'm trying to view from the .fbd files.
![Histogram Example Data from 80MHz](https://github.com/cgohlke/lfdfiles/assets/140131469/385f06d9-4d14-4b1c-85a5-490956e2781c)


-	Screenshots of the FastFLIM Setup from both 80MHz (decodable) and 20MHz (undecodable) measurements 
![Settings 80MHz](https://github.com/cgohlke/lfdfiles/assets/140131469/96b70fdd-b2d2-4c70-999b-6d98ae075ad7)
![Settings 20MHz](https://github.com/cgohlke/lfdfiles/assets/140131469/21be7c8f-845d-4198-8184-9cd3462edab5)


-	The ISS files for one of the undecodable examples previously attached - 
[Undecoded Example - all files.zip](https://github.com/cgohlke/lfdfiles/files/14477019/Undecoded.Example.-.all.files.zip)


As for the channels, measurement was taken in the 2nd  channel only for the 20MHz run of images and for the 80MHz run the 2nd and 4th channel were used.

Thanks again for your assistance and please let me know if I can provide anymore information.

**Comment by cgohlke** [comment]
Thanks for following up. I was able to decode the files with a newer version of VistaVision. The information I have about the 32-bit, 16 windows, 4 channels format seems wrong or does not apply to this firmware:

```python
        # 0b00000000000000000000000011111111 cross correlation phase
        # 0b00000000000000000000001111111111 cross correlation time  # 10 bit
        # 0b00000000000000000000010000000000 start of line marker
        # 0b00000000000000000000100000000000 start of frame marker
        # 0b00000000000000000001000000000000 ch0 photon
        # 0b00000000000000011110000000000000 ch0 window
        # 0b00000000000000100000000000000000 ch1 photon
        # 0b00000000001111000000000000000000 ch1 window
        # 0b00000000010000000000000000000000 ch2 photon
        # 0b00000111100000000000000000000000 ch2 window
        # 0b00001000000000000000000000000000 ch3 photon
        # 0b11110000000000000000000000000000 ch3 window
```

I tried a few simple variants of this format (moving markers to the end, etc) to no avail.

**Comment by cgohlke** [comment]
Two issues: 

1. This firmware writes the 32-bit as two 16-bit words in unexpected order. That's OK, I just wish it would be documented so reverse engineering would not be necessary.

2. ISS uses scanner settings not fully supported by the current lfdfiles implementation but it seem to work anyway. However, two of the sample files have a wrong dwell time in the metadata. You can override it manually:

```Python
import numpy
from lfdfiles import FlimboxFbd
from tifffile import imshow

with FlimboxFbd(
    'E5+17+32M-20MHz-cell1$XX2X.fbd', pixel_dwell_time=20
) as fbd:
    print(fbd)
    bins_times_markers = fbd.decode()
    frames = fbd.frames(bins_times_markers)
    image = fbd.asimage(bins_times_markers, frames, integrate_frames=1)
    print(image.shape)

imshow(numpy.mean(image[0, 1], axis=-1), show=True)
```
![Figure_3](https://github.com/cgohlke/lfdfiles/assets/483428/3f87fc7e-551f-4079-b010-f341da8c7b8a)

![Figure_1](https://github.com/cgohlke/lfdfiles/assets/483428/fbe6baa3-0f4c-45c4-97f8-98460d74d8a7)

**Comment by cgohlke** [comment]
This should be fixed in v2024.3.4.

**Comment by ghost** [comment]
Sorry but I ran the above code with the dwell time correction and received the following traceback for the same file previously sent ('E5+17+32M-20MHz-cell1$XX2X.fbd'). 

Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm 2023.1\plugins\python\helpers\pydev\pydevconsole.py", line 364, in runcode
    coro = func()
           ^^^^^^
  File "<input>", line 11, in <module>
  File "~\lfdfiles.py", line 3703, in frames
    self.laser_factor = laser_factors[frame_cluster]
                        ~~~~~~~~~~~~~^^^^^^^^^^^^^^^
IndexError: list index out of range

It is worth noting that print(fbd) indicates the laser_factor is 1.0 for this image. This is very different from the laser factor for the decodable (80MHz) images which are 2.007818644172267.

**Comment by cgohlke** [comment]
What does this print?:
```Python
import lfdfiles
print(lfdfiles.__version__)
```

**Comment by cgohlke** [comment]
> the laser factor for the decodable (80MHz) images which are 2.007818644172267.

This also indicates that the dwell time or some other scanner parameter is not quite right in the metadata. The laser factor should be very close to 1. As I mentioned, the current implementation for frame reconstruction is not using all ISS scanner parameters and of course those parameters are undocumented... 

BTW, I wanted to mention that lfdfiles can read ISS IFLI files, which contain "phasor" images. Maybe that is a better option for you than decoding FBD files.

**Comment by cgohlke** [comment]
> `File "~\lfdfiles.py", line 3703, in frames`
> `self.laser_factor = laser_factors[frame_cluster]`

That is version 2023.9.23. Please update to the latest version, currently 2024.3.4:
```
python -m pip install -U lfdfiles
```

**Comment by ghost** [comment]
My mistake, I had installed 2024.3.4 but clearly not correctly as 2023.9.23 was still the version being used. After uninstalling and reinstalling the package it's all working fine. Thank you again for all your help!
